version: '3.8'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'finnr@blueyonder.co.uk'
            PGADMIN_DEFAULT_PASSWORD: 'test'
        ports:
            - 16543:80
        volumes:
            - ./database/servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network
    srt_server:
        build:
            context: ./srt-server
            dockerfile: Dockerfile
        volumes:
            - ./srt-server:/server
        ports:
            - 7500:7500/udp
        command: sleep infinity

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./database/data

    srt-webserver:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./srt-server
networks:
    postgres-db-network:
        driver: bridge